language: java

sudo: required

before_install:
- wget https://releases.hashicorp.com/packer/1.0.4/packer_1.0.4_linux_amd64.zip
- unzip -o packer_1.0.4_linux_amd64.zip -d /usr/local/bin/
- rm packer_1.0.4_linux_amd64.zip
