language: java

sudo: required

before_install:
- wget https://releases.hashicorp.com/packer/1.0.4/packer_1.0.4_linux_amd64.zip
- unzip -o packer_1.0.4_linux_amd64.zip
- rm packer_1.0.4_linux_amd64.zip

env:
- BUILD_VERSION="1.0"

before_script:
- packer validate packerfile.json

script:
- packer build packerfile.json
